apiVersion: v2
name: apps
description: Umbrella chart that bundles the homelab applications
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: democratic-csi
    version: 0.1.0
    repository: "file://../democratic-csi"
    condition: apps.democraticCsi.enabled
  - name: grafana
    version: 0.1.0
    repository: "file://../grafana"
    condition: apps.grafana.enabled
  - name: metrics-server
    version: 0.1.0
    repository: "file://../metrics-server"
    condition: apps.metricsServer.enabled
  - name: prometheus
    version: 0.1.0
    repository: "file://../prometheus"
    condition: apps.prometheus.enabled

