apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-sdk
spec:
  provider:
    onepasswordSDK:
      vault: shimmer-labs 
      auth:
        serviceAccountSecretRef:
          name: op-service-account-token
          key: token