apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: 1password-sdk
spec:
  provider:
    onepasswordSDK:
      vault: Shimmer Labs
      auth:
        serviceAccountSecretRef:
          name: op-service-account-token
          key: token