---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-es
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    # Merge into the existing Argo CD secret so dex can read the client creds.
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: dex.authentik.clientID
      remoteRef:
        key: argocd.authentik.client/username
    - secretKey: dex.authentik.clientSecret
      remoteRef:
        key: argocd.authentik.client/credential