apiVersion: v2
name: external-secrets
description: GitOps control plane for the homelab cluster
type: application
version: 0.1.0
appVersion: "3.2.1"
dependencies:
  - name: external-secrets
    version: 1.1.1
    repository: https://charts.external-secrets.io
  - name: reloader
    version: 2.2.5
    repository: https://stakater.github.io/stakater-charts