external-secrets:
  grafanaDashboard:
    enabled: true

  metrics.service.enabled: true

  serviceMonitor:
    enabled: true
    namespace: prometheus
    interval: 30s
    scrapeTimeout: 10s

reloader:
  logFormat: json
  enableMetricsByNamespace: true

  deployment:
    replicas: 1

  serviceMonitor.enabled: true
  podMonitor.enabled: true
  