{{- if .Values.dbPassword.generate }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ .Release.Name }}-db-password
  namespace: {{ .Release.Namespace }}
spec:
  length: {{ .Values.dbPassword.length | default 32 }}
  symbols: {{ .Values.dbPassword.includeSymbols | default false }}
{{- end }}


