{{- if .Values.dbPassword.generate }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-db-auth
  namespace: {{ .Release.Namespace }}
spec:
  target:
    name: {{ .Values.dbPassword.secretName | default (printf "%s-db-auth" .Release.Name) }}
    creationPolicy: Owner
    template:
      data:
        password: "{{ `{{ .password }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          name: {{ .Release.Name }}-db-password
{{- end }}


