{{- $db := .Values.dbPassword | default (dict) }}
{{- if $db.generate }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ .Release.Name }}-db-password
  namespace: {{ .Release.Namespace }}
spec:
  length: {{ $db.length | default 32 }}
  symbols: {{ $db.symbols | default 0 }}
{{- end }}


