{{- $db := .Values.dbPassword | default (dict) }}
{{- if $db.generate }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-db-auth
  namespace: {{ .Release.Namespace }}
spec:
  target:
    name: {{ $db.secretName | default (printf "%s-db-auth" .Release.Name) }}
    creationPolicy: Owner
    template:
      data:
        password: "{{ `{{ .password }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          kind: Password
          apiVersion: generators.external-secrets.io/v1alpha1
          name: {{ .Release.Name }}-db-password
{{- end }}


