apiVersion: v2
name: metallb
description: Configures MetalLB to provide LoadBalancer IPs inside the homelab cluster
type: application
version: 0.1.0
appVersion: "0.15.3"
dependencies:
  - name: metallb
    version: 0.15.3
    repository: https://metallb.github.io/metallb


