apiVersion: v2
name: democratic-csi
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: democratic-csi
    version: 0.15.0
    repository: https://democratic-csi.github.io/charts
