apiVersion: v2
name: cn-pg
description: cloudnative-pg
type: application
version: 0.1.0
appVersion: "3.2.1"
dependencies:
  - name: cloudnative-pg
    version: 0.27.0
    repository: https://cloudnative-pg.github.io/charts
