apiVersion: v2
name: n8n
description: GitOps control plane for the homelab cluster
type: application
version: 0.1.0
appVersion: "1.16.9"
dependencies:
  - name: n8n
    version: 1.16.9
    repository: https://community-charts.github.io/helm-charts