{{- range $issuer := .Values.clusterIssuers }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $issuer.name }}
spec:
  acme:
    email: {{ $issuer.email }}
    server: {{ $issuer.server }}
    privateKeySecretRef:
      name: {{ $issuer.privateKeySecretName | default (printf "%s-account-key" $issuer.name) }}
    solvers:
{{ toYaml $issuer.solvers | indent 6 }}
---
{{- end }}

