---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: certmanager-es
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk
  target:
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: cloudflare-api-token/credential