cert-manager:
  installCRDs: true
  global:
    leaderElection:
      namespace: cert-manager
  extraArgs:
    - --cluster-resource-namespace=$(POD_NAMESPACE)
    - --enable-certificate-owner-ref=true
  webhook:
    timeoutSeconds: 10

clusterIssuers:
  - name: letsencrypt-staging
    email: certs@shimmerlabs.xyz
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretName: letsencrypt-staging-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
  - name: letsencrypt-prod
    email: certs@shimmerlabs.xyz
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretName: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token