cert-manager:
  installCRDs: true
  global:
    leaderElection:
      namespace: cert-manager
  extraArgs:
    - --cluster-resource-namespace=$(POD_NAMESPACE)
    - --enable-certificate-owner-ref=true
    - --dns01-recursive-nameservers=8.8.8.8:53,8.8.4.4:53
    - --dns01-recursive-nameservers-only=true
  webhook:
    timeoutSeconds: 10
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
      namespace: prometheus
      labels:
        release: kube-prometheus-stack
      prometheusInstance: kube-prometheus-stack

clusterIssuers:
  - name: letsencrypt-staging
    email: certs@shimmerlabs.xyz
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretName: letsencrypt-staging-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
  - name: letsencrypt-prod
    email: certs@shimmerlabs.xyz
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretName: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token