cilium:
  clustermesh.apiserver.metrics.serviceMonitor.enabled: true
  envoy:
    enabled: true
    prometheus.serviceMonitor.enabled: true

  envoyConfig:
    enabled: true

  ingressController:
    enabled: true
    default: false

  gatewayAPI:
    enabled: true

  hubble:
    metrics:
      serviceMonitor:
        enabled: true
    enabled: true
    relay:
      enabled: true
      prometheus:
        serviceMonitor.enabled: true
    ui:
      enabled: true

  operator.prometheus.serviceMonitor.enabled: true

  prometheus:
    serviceMonitor:
      enabled: true
      trustCRDsExist: true

  nodePort:
    enabled: true
    enableHealthCheck: true

  kubeProxyReplacement: "true"
 
hubbleIngress:
  enabled: true
  host: hubble.k8s.shimmerlabs.xyz
  ingressClassName: traefik
  entrypoints: websecure
  clusterIssuer: letsencrypt-prod
  tlsSecretName: hubble-ui-tls
  namespace: kube-system
  annotations: {}